window.CALENDAR_EVENTS = [
  { date: '2026-01-23', name: 'Winterlicious', city: 'Toronto', category: 'festival' },
  { date: '2026-05-02', name: 'Doors Open Toronto', city: 'Toronto', category: 'culture' },
  { date: '2026-06-12', name: 'FIFA World Cup Toronto', city: 'Toronto', category: 'sports' },
  { date: '2026-06-28', name: 'Pride Toronto Parade', city: 'Toronto', category: 'culture' },
  { date: '2026-08-21', name: 'CNE Opening Day', city: 'Toronto', category: 'festival' },
  { date: '2026-09-10', name: 'TIFF Opening', city: 'Toronto', category: 'culture' },
  { date: '2026-01-31', name: 'Hamilton Winterfest', city: 'Hamilton', category: 'festival' },
  { date: '2026-05-02', name: 'Doors Open Hamilton', city: 'Hamilton', category: 'culture' },
  { date: '2026-07-31', name: 'Festival of Friends', city: 'Hamilton', category: 'festival' },
  { date: '2026-05-15', name: 'Canada Literature Festival', city: 'Mississauga', category: 'culture' },
  { date: '2026-06-12', name: 'Mississauga Halal Food Festival', city: 'Mississauga', category: 'festival' },
  { date: '2026-07-24', name: 'Bollywood Monster Mashup', city: 'Mississauga', category: 'festival' },
  { date: '2026-08-07', name: 'Mississauga Latin Festival', city: 'Mississauga', category: 'festival' },
  { date: '2026-04-26', name: 'FOLD Festival', city: 'Brampton', category: 'culture' },
  { date: '2026-05-22', name: "Rotary Rib'n'Roll", city: 'Brampton', category: 'festival' },
  { date: '2026-07-10', name: 'Carabram', city: 'Brampton', category: 'festival' },
  { date: '2026-02-07', name: 'Vaughan Winterfest', city: 'Vaughan', category: 'festival' },
  { date: '2026-09-18', name: 'Vaughan Culture Days', city: 'Vaughan', category: 'culture' },
  { date: '2026-09-26', name: 'Doors Open Markham', city: 'Markham', category: 'culture' },
  { date: '2026-04-16', name: 'Niagara Falls Elvis Festival', city: 'Niagara', category: 'culture' },
  { date: '2026-06-05', name: 'Niagara Falls Comic Con', city: 'Niagara', category: 'culture' },
  { date: '2026-07-31', name: 'Niagara Asian Night Market', city: 'Niagara', category: 'culture' },
  { date: '2026-10-31', name: '17U OVA Tournament', city: 'Vipers Elite', category: 'team' },
  { date: '2026-11-06', name: '18U OVA Tournament', city: 'Vipers Elite', category: 'team' },
  { date: '2027-01-15', name: '18U OVA Tournament', city: 'Vipers Elite', category: 'team' },
  { date: '2027-04-16', name: '17U Provincials', city: 'Vipers Elite', category: 'team' },
  { date: '2027-04-23', name: '18U Provincials', city: 'Vipers Elite', category: 'team' }
];
